services:
  dragteamapi:
    build:
      context: .
      dockerfile: DragTeamAPI/Dockerfile

    ports:
      - "8080:8080"

    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection1: "Server=tcp:dragteamserver.database.windows.net,1433;Initial Catalog=DragTeamDB;Persist Security Info=False;User ID=ScarlettDragTeam;Password=Chanel26;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"
    depends_on:
      - sqlserver

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest

    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "DragTeam@2026"

    ports:
      - "1433:1433"

    volumes:
      - sqlserver_data:/var/opt/mssql

volumes:
  sqlserver_data: